import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders  } from '@angular/common/http';
import { Observable, of } from 'rxjs';
import { HttpClientModule } from '@angular/common/http';
import { Path } from 'three';


@Injectable({
  providedIn: 'root'
})


export class ApiFetchService {

  private apiUrl = 'http://10.91.89.91:3003';
  private saltKey = 'Clove@$martCity';

  public dummy_data = [{ "data" : [
    {
        "prj_id": 1,
        "project_name": "Hon'ble MLAs and MLCs and AIS Officers - Housing",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 1,
        "pmc_id": "",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 2,
        "project_name": "Bungalows for Principal Secretaries & Secretaries",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 2,
        "pmc_id": "",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 3,
        "project_name": "Bungalows for Hon'ble Ministers & Hon'ble Judges",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 3,
        "pmc_id": "",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 4,
        "project_name": "Happy Nest",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 1,
        "pmc_id": "1",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": 14,
        "sub_prj_name": " Amaravathi_HappyNest_Block-DL",
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 4,
        "project_name": "Happy Nest",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 1,
        "pmc_id": "1",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": 13,
        "sub_prj_name": " Amaravathi_HappyNest_Block-DK",
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 4,
        "project_name": "Happy Nest",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 1,
        "pmc_id": "1",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": 12,
        "sub_prj_name": " Amaravathi_HappyNest_Block-DJ",
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 4,
        "project_name": "Happy Nest",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 1,
        "pmc_id": "1",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": 11,
        "sub_prj_name": " Amaravathi_HappyNest_Block-DI",
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 4,
        "project_name": "Happy Nest",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 1,
        "pmc_id": "1",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": 10,
        "sub_prj_name": " Amaravathi_HappyNest_Block-DH",
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 4,
        "project_name": "Happy Nest",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 1,
        "pmc_id": "1",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": 9,
        "sub_prj_name": " Amaravathi_HappyNest_Block-DG",
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 4,
        "project_name": "Happy Nest",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 1,
        "pmc_id": "1",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": 8,
        "sub_prj_name": " Amaravathi_HappyNest_Block-DF",
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 4,
        "project_name": "Happy Nest",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 1,
        "pmc_id": "1",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": 7,
        "sub_prj_name": " Amaravathi_HappyNest_Block-DE",
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 4,
        "project_name": "Happy Nest",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 1,
        "pmc_id": "1",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": 6,
        "sub_prj_name": "Basement 2",
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 4,
        "project_name": "Happy Nest",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 1,
        "pmc_id": "1",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": 5,
        "sub_prj_name": "Basement 1",
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 4,
        "project_name": "Happy Nest",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 1,
        "pmc_id": "1",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": 4,
        "sub_prj_name": " Amaravathi_HappyNest_Block-D",
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 4,
        "project_name": "Happy Nest",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 1,
        "pmc_id": "1",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": 3,
        "sub_prj_name": " Amaravathi_HappyNest_Block-C",
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 4,
        "project_name": "Happy Nest",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 1,
        "pmc_id": "1",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": 2,
        "sub_prj_name": " Amaravathi_HappyNest_Block-B",
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 4,
        "project_name": "Happy Nest",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 1,
        "pmc_id": "1",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": 1,
        "sub_prj_name": " Amaravathi_HappyNest_Block-A",
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 5,
        "project_name": "Project Office",
        "dept_id": 2,
        "division_id": 3,
        "contractor_id": 4,
        "pmc_id": "1",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 6,
        "project_name": "High Court",
        "dept_id": 2,
        "division_id": 3,
        "contractor_id": 1,
        "pmc_id": "2",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 7,
        "project_name": "Assembly - Structure",
        "dept_id": 2,
        "division_id": 3,
        "contractor_id": 5,
        "pmc_id": "2",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 8,
        "project_name": "Zone - 1A",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 3,
        "pmc_id": "3",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 9,
        "project_name": "Zone - 1B",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 3,
        "pmc_id": "3",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 10,
        "project_name": "Zone - 2A",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 3,
        "pmc_id": "4",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 11,
        "project_name": "Zone - 2B",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 3,
        "pmc_id": "4",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 12,
        "project_name": "Zone - 3A",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 6,
        "pmc_id": "5",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 13,
        "project_name": "Zone - 3B",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 7,
        "pmc_id": "5",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 14,
        "project_name": "Zone - 4",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 6,
        "pmc_id": "4",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 15,
        "project_name": "Zone - 5A",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 3,
        "pmc_id": "5",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 16,
        "project_name": "Zone - 5C",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 3,
        "pmc_id": "5",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 17,
        "project_name": "Zone - 5B",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 6,
        "pmc_id": "5",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 18,
        "project_name": "Zone - 5D",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 3,
        "pmc_id": "5",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 19,
        "project_name": "Zone - 6",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 7,
        "pmc_id": "4",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 20,
        "project_name": "Zone - 7",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 5,
        "pmc_id": "3",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 21,
        "project_name": "Zone - 9",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 7,
        "pmc_id": "5",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 22,
        "project_name": "Zone - 9A",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 7,
        "pmc_id": "5",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 23,
        "project_name": "Zone - 10",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 6,
        "pmc_id": "4",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 24,
        "project_name": "Zone - 12",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 1,
        "pmc_id": "3",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 25,
        "project_name": "Zone - 12A",
        "dept_id": 1,
        "division_id": 1,
        "contractor_id": 7,
        "pmc_id": "3",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 26,
        "project_name": "E3 Road - Phase I",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 1,
        "pmc_id": "4",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 27,
        "project_name": "E6 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 6,
        "pmc_id": "4",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 28,
        "project_name": "E8 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 6,
        "pmc_id": "4",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 29,
        "project_name": "E9 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 6,
        "pmc_id": "4",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 30,
        "project_name": "E14 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 7,
        "pmc_id": "4",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 31,
        "project_name": "N6 Utilities",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 7,
        "pmc_id": "4",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 32,
        "project_name": "N9 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 3,
        "pmc_id": "4",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 33,
        "project_name": "N11 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 6,
        "pmc_id": "4",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 34,
        "project_name": "N12 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 1,
        "pmc_id": "4",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 35,
        "project_name": "N15 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 1,
        "pmc_id": "4",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 36,
        "project_name": "N18 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 3,
        "pmc_id": "4",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 37,
        "project_name": "Flood Works - KV, PV, Sakhamuru Reservoir",
        "dept_id": 1,
        "division_id": 5,
        "contractor_id": 8,
        "pmc_id": "6",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 38,
        "project_name": "Flood Works - Gravity Canal, Krishnayapalem Reservoir",
        "dept_id": 1,
        "division_id": 5,
        "contractor_id": 8,
        "pmc_id": "6",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 39,
        "project_name": "Flood Works - Neerukonda Reservoir",
        "dept_id": 1,
        "division_id": 5,
        "contractor_id": 1,
        "pmc_id": "6",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 40,
        "project_name": "E15 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 3,
        "pmc_id": "7",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 41,
        "project_name": "E16 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 1,
        "pmc_id": "8",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 42,
        "project_name": "E3 Road - Phase II",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 1,
        "pmc_id": "9",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 43,
        "project_name": "N13 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 6,
        "pmc_id": "7",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 44,
        "project_name": "N5 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 1,
        "pmc_id": "8",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 45,
        "project_name": "E4 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 7,
        "pmc_id": "4",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 46,
        "project_name": "N3A and N3B Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 9,
        "pmc_id": "8",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 47,
        "project_name": "E7 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 3,
        "pmc_id": "4",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 48,
        "project_name": "N7 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 6,
        "pmc_id": "9",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 49,
        "project_name": "N2 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 3,
        "pmc_id": "8",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 50,
        "project_name": "E10 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 7,
        "pmc_id": "9",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 51,
        "project_name": "N1 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 3,
        "pmc_id": "8",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 52,
        "project_name": "N4 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 9,
        "pmc_id": "9",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 53,
        "project_name": "E13 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 6,
        "pmc_id": "7",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 54,
        "project_name": "E5 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 3,
        "pmc_id": "4",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 55,
        "project_name": "N17 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 9,
        "pmc_id": "9",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 56,
        "project_name": "N8 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 1,
        "pmc_id": "7",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 57,
        "project_name": "N10 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 6,
        "pmc_id": "9",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 58,
        "project_name": "E12 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 3,
        "pmc_id": "9",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 59,
        "project_name": "N14 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 6,
        "pmc_id": "9",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 60,
        "project_name": "E11 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 7,
        "pmc_id": "7",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 61,
        "project_name": "E2 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 3,
        "pmc_id": "4",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 62,
        "project_name": "N16 Road",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 9,
        "pmc_id": "9",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 63,
        "project_name": "NGO (Housing+Ext. Infra) - 12 Towers",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 5,
        "pmc_id": "5",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 64,
        "project_name": "NGO (Housing+Ext. Infra) - 9 Towers",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 5,
        "pmc_id": "5",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 65,
        "project_name": "GOs and Group D employees - Housing",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 10,
        "pmc_id": "1",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 66,
        "project_name": "GOs and Group D employees - External Infra",
        "dept_id": 2,
        "division_id": 4,
        "contractor_id": 10,
        "pmc_id": "",
        "fund_id": 1,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 67,
        "project_name": "GAD Tower - Structure",
        "dept_id": 2,
        "division_id": 3,
        "contractor_id": 1,
        "pmc_id": "10",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 68,
        "project_name": "Tower 1 and 2 - Structure",
        "dept_id": 2,
        "division_id": 3,
        "contractor_id": 10,
        "pmc_id": "10",
        "fund_id": 2,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 69,
        "project_name": "Tower 3 and 4 - Structure",
        "dept_id": 2,
        "division_id": 3,
        "contractor_id": 5,
        "pmc_id": "10",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 70,
        "project_name": "3 PEB Structures near Project Office",
        "dept_id": 2,
        "division_id": 3,
        "contractor_id": 1,
        "pmc_id": "1",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 71,
        "project_name": "E15 Road - Extn. upto NH-16",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 7,
        "pmc_id": "8",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 72,
        "project_name": "E13 Road - Extn. upto NH-16",
        "dept_id": 1,
        "division_id": 2,
        "contractor_id": 7,
        "pmc_id": "8",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 73,
        "project_name": "400KV DC lines rerouting",
        "dept_id": 3,
        "division_id": 6,
        "contractor_id": 11,
        "pmc_id": "",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    },
    {
        "prj_id": 74,
        "project_name": "220KV EHV lines rerouting",
        "dept_id": 3,
        "division_id": 6,
        "contractor_id": 3,
        "pmc_id": "",
        "fund_id": 3,
        "status": 1,
        "sub_prj_id": null,
        "sub_prj_name": null,
        "sub_prj_type_id": null,
        "model_id": null
    }
  ]
}];

  constructor(private http: HttpClient) {}

  private getAuthHeaders(): HttpHeaders {
    return new HttpHeaders({
      
      'X-Salt-Key': this.saltKey
    });
  }

  get_list_projs(): Observable<any[]> {
    return this.http.get<any[]>(`${this.apiUrl}/get_projects_mast`,
      {
        headers: this.getAuthHeaders()
      }
    );
  }

  

  get_list_projs1(): Observable<any[]> {
    // Return dummy_data.data as an Observable
    return of(this.dummy_data);
  }




  
  getListMethod1(): Observable<any[]> {
    return this.http.get<any[]>(`${this.apiUrl}/method1`,
      {
        headers: this.getAuthHeaders()
      }
    );
  }

}



@Injectable({
  providedIn: 'root'
})

export class JsonFetchService {

  private Base_dir = './repos/';

  constructor(private http: HttpClient) {}
  
  agcFolders: string[] = [];
  
  get_fetch_dirs(subDir: string): { observable: Observable<string[]>, baseDir: string } {
    const tmp_path = this.Base_dir + subDir + "/data.json";
    return {
      observable: this.http.get<string[]>(tmp_path),
      baseDir: this.Base_dir
    };
  }
}
